networks:
  hybrid_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.11.0/24

services:
  node_a:
    container_name: hm_node_a
    build:
      context: ..
      dockerfile: /Dockerfile
      args:
        CFGFILE: "nodes/Alice/config.json"
    networks:
      hybrid_network:
        ipv4_address: 10.10.11.245  # Static IP for Node A

  node_b:
    container_name: hm_node_b
    build:
      context: ..
      dockerfile: /Dockerfile
      args:
        CFGFILE: "nodes/Bob/config.json"
    networks:
      hybrid_network:
        ipv4_address: 10.10.11.246  # Static IP for Node B

